{{ config(materialized='ephemeral') }}

SELECT
_DATA:"ACCOUNT_TYPE"::STRING AS ACCOUNT_TYPE,
_DATA:"CUSTOMER_ID"::NUMBER AS CUSTOMER_ID,
_DATA:"FIRST_NAME"::STRING AS FIRST_NAME,
_DATA:"MIDDLE_NAME"::STRING AS MIDDLE_NAME,
_DATA:"LAST_NAME"::STRING AS LAST_NAME,
_DATA:"ACCOUNT_DETAILS"[0]:"Address":"Billing"::STRING AS Billing_Address,
_DATA:"ACCOUNT_DETAILS"[0]:"Address":"Residential"::STRING AS Residential_Address,
_DATA:"ACCOUNT_DETAILS"[0]:"Banking":"accountNumber"::STRING AS ACCNO,
_DATA:"ACCOUNT_DETAILS"[0]:"Banking":"balance"::NUMBER AS BALANCE,
_DATA:"ACCOUNT_DETAILS"[0]:"Banking":"branch"::STRING AS BRANCH
FROM MYDB.AZURE_BLOB_STORAGE_JSON.JSON_DATA